SRC=main.c Stack.c ReversedPolishNotation.c Token.c
EXEC_NAME=lab4
HEADERS=Stack.h ReversedPolishNotation.h Token.h
CFLAGS=-O0 -Wall -Werror -g3 -o $(EXEC_NAME)

all: $(HEADERS)
	gcc $(CFLAGS) $(SRC)
clean:
	rm $(EXEC_NAME)
